title: Minimal Docs
show_downloads: false
theme: jekyll-theme-minimal
description: >
  Minimal theme repurposed for project documentation
  <hr/>
  <a href="navigation.html">Navigation</a><br/>
  <div class="nav">
  <a href="indent.html">Indentation</a><br/>
  </div>
  <br/><hr/>